const assert = require("node:assert/strict");
const test = require("node:test");

const {
  isLocalCommandArtifact,
  isWarmupMessage,
  isUnusableSessionPreview,
  isBareSlashCommand,
} = require("../dist/native-transcript-filter");

// Verbatim from a /usage transcript in ~/.claude/projects. Both user messages
// in the file look like real prompts to a scan that only checks for one.
const CAVEAT =
  "<local-command-caveat>Caveat: The messages below were generated by the user "
  + "while running local commands. DO NOT respond to these messages or otherwise "
  + "consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
const COMMAND =
  "<command-name>/usage</command-name>\n            <command-message>usage</command-message>"
  + "\n            <command-args></command-args>";

test("both halves of a slash-command transcript are recognised", () => {
  assert.ok(isLocalCommandArtifact(CAVEAT));
  assert.ok(isLocalCommandArtifact(COMMAND));
  assert.ok(isUnusableSessionPreview(CAVEAT));
  assert.ok(isUnusableSessionPreview(COMMAND));
});

test("a real prompt is never mistaken for one", () => {
  for (const real of [
    "Last night I tried to use Fable to knock out a couple tickets",
    "why do we have my load shed thing that is controlled",
    "explain <command-name> tags to me",
    "run /usage and tell me what it says",
  ]) {
    assert.equal(isLocalCommandArtifact(real), false, real);
    assert.equal(isUnusableSessionPreview(real), false, real);
  }
});

test("warmup and empty previews stay unusable", () => {
  assert.ok(isWarmupMessage("Warmup"));
  assert.ok(isWarmupMessage("  warmup  "));
  assert.ok(isUnusableSessionPreview(""));
  assert.ok(isUnusableSessionPreview("   "));
  assert.equal(isWarmupMessage("warmup the cache please"), false);
});

test("a bare slash command is spotted, a sentence starting with one is not", () => {
  for (const bare of ["/usage", "  /context  ", "/cost", "/agent:review"]) {
    assert.ok(isBareSlashCommand(bare), bare);
  }
  for (const notBare of ["/usage and then explain it", "usage", "", "/"]) {
    assert.equal(isBareSlashCommand(notBare), false, notBare);
  }
});

const {
  isLocalCommandOnlySession,
  isLocalCommandOnlyEntry,
  listedPreview,
} = require("../dist/native-transcript-filter");
const { mergeSessionListBase } = require("../dist/session-list-snapshot");

const commandBlock = (name) =>
  `<command-name>/${name}</command-name>\n  <command-message>${name}</command-message>`;

test("the rule is about local commands, not about /usage", () => {
  // Keyed on the wrapper Claude Code writes, so every command is covered.
  for (const name of ["usage", "context", "cost", "doctor", "clear", "agents", "some-future-command"]) {
    assert.ok(isLocalCommandArtifact(commandBlock(name)), name);
    assert.ok(isLocalCommandOnlySession({ firstPrompt: commandBlock(name) }), name);
  }
});

test("a session is only filtered when that is all there is", () => {
  const cmd = commandBlock("usage");
  // Ran a command, then actually talked: the summary is real work.
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: cmd, summary: "Fixing the archive bug" }),
    false,
  );
  // The user named it, so they mean to keep it.
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: cmd, customTitle: "usage check" }),
    false,
  );
  // No evidence either way is not evidence of a command.
  assert.equal(isLocalCommandOnlySession({}), false);
  assert.equal(isLocalCommandOnlySession({ firstPrompt: "", summary: "" }), false);
  // Both halves point the same way.
  assert.ok(isLocalCommandOnlySession({ firstPrompt: cmd, summary: CAVEAT }));
});

// The row that survived the first cut, reproduced from the session card:
// title "/usage", preview "<command-name>/usage</command-name>...". The SDK
// derives a title and summary from the command name, and neither is a
// <command-*> block, so a rule that demanded every field be one kept the row.
test("a slash-command transcript with a derived /usage title is filtered", () => {
  assert.ok(
    isLocalCommandOnlySession({
      firstPrompt: COMMAND,
      summary: "/usage",
      customTitle: "/usage",
    }),
  );
  assert.ok(isLocalCommandOnlySession({ firstPrompt: COMMAND, summary: "/usage" }));
  assert.ok(isLocalCommandOnlySession({ firstPrompt: COMMAND, customTitle: "/usage" }));
  assert.ok(isLocalCommandOnlySession({ firstPrompt: CAVEAT, summary: "/usage" }));
});

// Running /usage from the app leaves the same throwaway transcript, and the
// store's title and preview are derived from the same command text.
test("a tracked slash-command session is filtered too", () => {
  assert.ok(
    isLocalCommandOnlySession(
      { firstPrompt: COMMAND, summary: "/usage" },
      { title: "/usage", messagePreview: COMMAND },
    ),
  );
  assert.ok(
    isLocalCommandOnlySession(
      { firstPrompt: COMMAND },
      { title: "Untitled", messagePreview: COMMAND },
    ),
  );
});

// The reason the rule needs a real command block and not just a slash command:
// a conversation can open with one and then be entirely real.
test("a session that opened with a slash command and continued is kept", () => {
  assert.equal(isLocalCommandOnlySession({ firstPrompt: "/compact" }), false);
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: "/model", summary: "Refactor the parser" }),
    false,
  );
});

test("a real session is never filtered", () => {
  assert.equal(
    isLocalCommandOnlySession({
      firstPrompt: "fix the login bug",
      summary: "Debugging the login flow",
    }),
    false,
  );
  assert.equal(isLocalCommandOnlySession({}), false);
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: COMMAND, summary: "Reviewed the usage numbers" }),
    false,
  );
});

// A title someone typed is real content and outranks the command block.
test("a user-set title keeps the session listed", () => {
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: COMMAND, customTitle: "Usage check" }),
    false,
  );
  assert.equal(
    isLocalCommandOnlySession({ firstPrompt: COMMAND }, { title: "Usage check" }),
    false,
  );
});

// Rows exactly as the session list showed them. A tracked session is listed
// straight out of the store and never meets the SDK converters, so the check
// has to run on the assembled row as well.
const listRow = (id, title, messagePreview) => ({
  id,
  title,
  messagePreview,
  createdAt: "2026-08-12T00:00:00.000Z",
  lastActive: "2026-08-12T00:00:00.000Z",
});

test("an assembled /usage row is dropped from the list", () => {
  assert.ok(isLocalCommandOnlyEntry(listRow("a", "/usage", COMMAND)));
  assert.ok(isLocalCommandOnlyEntry(listRow("b", "Untitled", COMMAND)));
  assert.ok(isLocalCommandOnlyEntry(listRow("c", "/usage", CAVEAT)));
});

// This one is real work that happened to end on a command.
test("a real session with a command preview stays listed", () => {
  assert.equal(
    isLocalCommandOnlyEntry(
      listRow("d", "Validate and test Movespeed USB drive", "<local-command-stdout>Bye!</local-command-stdout>"),
    ),
    false,
  );
  assert.equal(
    isLocalCommandOnlyEntry(listRow("e", "Bobby", "Run it elevated: powershell -File ...")),
    false,
  );
});

test("a preview that is only a command artifact is not shown", () => {
  assert.equal(listedPreview("<local-command-stdout>Bye!</local-command-stdout>"), "");
  assert.equal(listedPreview(COMMAND), "");
  assert.equal(listedPreview("Run it elevated"), "Run it elevated");
  assert.equal(listedPreview(undefined), "");
});

test("the list drops command rows and cleans the previews that remain", () => {
  const merged = mergeSessionListBase(
    [
      listRow("a", "/usage", COMMAND),
      listRow("b", "Validate and test Movespeed USB drive", "<local-command-stdout>Bye!</local-command-stdout>"),
      listRow("c", "Bobby", "Run it elevated"),
    ],
    null,
    new Set(),
  );
  assert.deepEqual(
    merged.map((row) => [row.title, row.messagePreview]),
    [
      ["Validate and test Movespeed USB drive", ""],
      ["Bobby", "Run it elevated"],
    ],
  );
});

test("a command row is dropped from the native half of the merge too", () => {
  const merged = mergeSessionListBase(
    [],
    [listRow("a", "/usage", COMMAND), listRow("b", "Real work", "fix the parser")],
    new Set(),
  );
  assert.deepEqual(merged.map((row) => row.title), ["Real work"]);
});
