const assert = require("node:assert/strict");
const test = require("node:test");

const {
  isLocalCommandArtifact,
  isWarmupMessage,
  isUnusableSessionPreview,
  isBareSlashCommand,
} = require("../dist/native-transcript-filter");

// Verbatim from a /usage transcript in ~/.claude/projects. Both user messages
// in the file look like real prompts to a scan that only checks for one.
const CAVEAT =
  "<local-command-caveat>Caveat: The messages below were generated by the user "
  + "while running local commands. DO NOT respond to these messages or otherwise "
  + "consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
const COMMAND =
  "<command-name>/usage</command-name>\n            <command-message>usage</command-message>"
  + "\n            <command-args></command-args>";

test("both halves of a slash-command transcript are recognised", () => {
  assert.ok(isLocalCommandArtifact(CAVEAT));
  assert.ok(isLocalCommandArtifact(COMMAND));
  assert.ok(isUnusableSessionPreview(CAVEAT));
  assert.ok(isUnusableSessionPreview(COMMAND));
});

test("a real prompt is never mistaken for one", () => {
  for (const real of [
    "Last night I tried to use Fable to knock out a couple tickets",
    "why do we have my load shed thing that is controlled",
    "explain <command-name> tags to me",
    "run /usage and tell me what it says",
  ]) {
    assert.equal(isLocalCommandArtifact(real), false, real);
    assert.equal(isUnusableSessionPreview(real), false, real);
  }
});

test("warmup and empty previews stay unusable", () => {
  assert.ok(isWarmupMessage("Warmup"));
  assert.ok(isWarmupMessage("  warmup  "));
  assert.ok(isUnusableSessionPreview(""));
  assert.ok(isUnusableSessionPreview("   "));
  assert.equal(isWarmupMessage("warmup the cache please"), false);
});

test("a bare slash command is spotted, a sentence starting with one is not", () => {
  for (const bare of ["/usage", "  /context  ", "/cost", "/agent:review"]) {
    assert.ok(isBareSlashCommand(bare), bare);
  }
  for (const notBare of ["/usage and then explain it", "usage", "", "/"]) {
    assert.equal(isBareSlashCommand(notBare), false, notBare);
  }
});
